export const TRENDING_STORIES = [
	{
		id: 1,
		rank: 1,
		title: 'I replaced my native iOS app with a cross platform web app and no-one noticed',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
	{
		id: 2,
		rank: 2,
		title: 'Johnny Depp Will Likely Lose His $50M Defamation Case',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
	{
		id: 3,
		rank: 3,
		title: 'PyScript — unleash the power of Python in your browser',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
	{
		id: 4,
		rank: 4,
		title: 'My Statement with Michelle on the Draft Supreme Court Decision to Overturn Roe v. Wade',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
	{
		id: 5,
		rank: 5,
		title: 'Austria buys JavaScript from Brendan Eich.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
	{
		id: 6,
		rank: 6,
		title: 'What My Grandmother Was Trying to Tell Me.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
	},
];

export const BLOGS = [
	{
		id: 1,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 2,
		image: 'https://via.placeholder.com/200',
		title: 'Netflix’s “Old Enough” as Viewed by a Mother in Japan',
		subtitle: 'Are those little ones really “old enough” to run errands?',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 3,
		image: 'https://via.placeholder.com/200',
		title: 'Lo-fi Hip Hop and POV Playlists are symptoms of late capitalism',
		subtitle: 'Contradictory, these trends aim to provide comfort for the audience while feeding an original loop of suffering',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 4,
		image: 'https://via.placeholder.com/200',
		title: 'How to Add Value as a Data Analyst',
		subtitle: 'The journey to becoming a “real” data analyst',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 5,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 6,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 7,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 8,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: null,
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 9,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
	{
		id: 10,
		image: 'https://via.placeholder.com/200',
		title: 'Just the Gods Hurling Javelins of Lightning Above Mesa Verde',
		subtitle: 'It was better than any light show from Pink Floyd or Genesis.',
		author_name: 'John Doe',
		author_img: 'https://via.placeholder.com/150',
		author_link: '#',
		publication: 'The Masterpiece',
		created_at: '2020-01-01',
		updated_at: '2020-01-01',
		reading_time: '1 min read',
		category: 'Nature',
	},
]